config/routes.rb
HengageTest::Application.routes.draw do
  root :to => 'users#index'
  devise_for :users
  resources :users, except: :destroy
  resources :projects, except: :destroy
  resources :time_blocks, except: :show
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :time_blocks

  attr_accessible :name
  
  validates_presence_of :name
end

app/models/time_block.rb
class TimeBlock < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  attr_accessible :end_time, :start_time, :project_id, :user_id
  
  validates_presence_of :user_id
  validates_presence_of :project_id
  validates_presence_of :start_time
  validates_presence_of :end_time
  validate :sequence_of_times
  validate :against_overlapping
  
  def other_time_blocks
    otb = TimeBlock.where(:project_id => project_id).where(:user_id => user_id)
    otb = otb.where('id <> ?', id) if persisted?
    otb
  end
  
  def includes?(time)
    start_time <= time and time <= end_time ? true : false
  end
  
  def contains?(other_time_block)
    other_time_block.includes?(start_time) or other_time_block.includes?(end_time)
  end
  
  def seconds_worked
    end_time - start_time
  end
  
  private
  
  def sequence_of_times
    if start_time.is_a? Time and end_time.is_a? Time and start_time >= end_time
      errors.add(:end_time, 'must be after the start time')
    end
  end
  
  def against_overlapping
    # Make all attributes are valid and functional
    if start_time.is_a? Time and end_time.is_a? Time and project_id.present? and user_id.present?
      # Iterate through other time blocks of the same user and project
      otbs = other_time_blocks
      unless otbs.empty?
        # Initialize iteration
        other_time_block = otbs.pop
        while other_time_block and errors.blank?
          # Check for overlap with contains? and includes? methods
          if other_time_block.contains?(self) or contains?(other_time_block)
            self.errors[:base] << 'this time overlaps with other time blocks'
          end
          # Continue to interate
          other_time_block = otbs.pop
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :time_blocks
  has_many :projects, :through => :time_blocks

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable, :registerable
  # :recoverable, :rememberable, :trackable
  devise :database_authenticatable
  # After reading the instructions again, devise' database authenticable solution
  # seems to be more robust of a solution than was needed:
  # 'foobar' is the default password *not* the required password

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :admin
  

  before_create :set_default_password
  
  validates :email, :presence => true, :format => {:with => /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b$/i},
                    :uniqueness => true

  def admin?
    admin
  end
  
  private 
  
  def set_default_password
    self.password = 'foobar' if password.nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :authenticate_user!

  private 
  
  def require_admin!
    redirect_to :root, :alert => 'Stop!  You must be an admin to do that!' unless current_user.admin?
  end
  
  def time_from_params(time_string)
    Time.local(
      params[:report][time_string + '(1i)'], 
      params[:report][time_string + '(2i)'],
      params[:report][time_string + '(3i)'],
      params[:report][time_string + '(4i)'],
      params[:report][time_string + '(5i)'])
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_admin!, :only => [:new, :edit, :create, :update]
  
  def index
    @projects = Project.page(params[:page])
  end

  def show
    params[:report].present? ? (@start_time = time_from_params('start_time')) : (@start_time = Time.zone.now - 1.day)
    params[:report].present? ? (@end_time = time_from_params('end_time')) : (@end_time = Time.zone.now)
    @project = Project.find(params[:id])
    if @start_time < @end_time
      @project_report = ProjectReport.new(:project_id => @project.id, :start_time => @start_time, :end_time => @end_time)
    else
      redirect_to project_path(@project), alert: 'The times you\'ve entered don\'t make sense!!!'
    end
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      flash[:alert] = 'Oh noes!  Something went wrong.'
      render action: "new"
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      flash[:alert] = 'Gosh Darn!  Something went wrong.'
      render action: "edit"
    end
  end
  
end

app/controllers/time_blocks_controller.rb
class TimeBlocksController < ApplicationController
  def index
    @time_blocks = current_user.time_blocks.includes(:project).page(params[:page])
  end

  def new
    @time_block = TimeBlock.new
    @projects = Project.all
  end

  def edit
    @time_block = current_user.time_blocks.where(:id => params[:id]).first
    @projects = Project.all
  end

  def create
    @time_block = current_user.time_blocks.build(params[:time_block])

    if @time_block.save
      redirect_to time_blocks_path, notice: 'Time Block saved!  Woohoo!'
    else
      @projects = Project.all
      flash[:alert] = 'Blast!  Something wasn\'t quite right'
      render action: "new"
    end
  end

  def update
    @time_block = current_user.time_blocks.where(:id => params[:id]).first

    if @time_block.update_attributes(params[:time_block])
      redirect_to time_blocks_path, notice: 'Time block was successfully updated.'
    else
      @projects = Project.all
      flash[:alert] = 'Shoot!  Something wasn\'t quite right'
      render action: "edit" 
    end
  end

  def destroy
    @time_block = current_user.time_blocks.where(:id => params[:id]).first
    @time_block.destroy
    redirect_to time_blocks_url, notice: 'The Time Block has been destroyed!  Yaarrr!'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  end

  def index
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin!, :only => [:new, :edit, :create, :update]

  def index
    @users = User.page(params[:page])
  end

  def show
    params[:report].present? ? (@start_time = time_from_params('start_time')) : (@start_time = Time.zone.now - 1.day)
    params[:report].present? ? (@end_time = time_from_params('end_time')) : (@end_time = Time.zone.now)
    @user = User.find(params[:id])
    if @start_time < @end_time
      @user_report = UserReport.new(:user_id => @user.id, :start_time => @start_time, :end_time => @end_time)
    else
      redirect_to user_path(@user), alert: 'The times you\'ve entered don\'t make sense!!!  May get strange response!'
    end
  end

  def new
    @user = User.new()
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save 
      redirect_to user_path(@user), notice: 'Saved!  You\'re awesome!'
    else
      flash.now[:alert] = 'Oh no!  Something wasn\'t quite right'
      render action: 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user]) 
      redirect_to @user, notice: 'Saved!  You\'re awesome!'
    else
      flash.now[:alert] = 'Ayee yeeah! Something wasn\'t quite right!'
      render action: 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_time(time)
    time.strftime('%b %d, %Y @ %H:%M:%S') if time.is_a? Time
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def rounded_hours_from_seconds(seconds)
    i = seconds/60
    r = seconds % 60.0 
    if r >= 7.5 and r < 22.5
      i += 0.25
    elsif r >= 22.5 and r < 37.5
      i += 0.5
    elsif r >= 37.5 and r < 52.5
      i += 0.75
    elsif  r >= 52.5
      i += 1.0
    end
    i
  end
end

app/helpers/time_blocks_helper.rb
module TimeBlocksHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HengageTest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p id='navigation'>
		<% if current_user %>
			<strong>
				<em>Navigate!</em>
				<%= link_to 'Users', users_path %>
				<%= link_to 'Projects', projects_path %>
				<%= link_to 'Time Blocks', time_blocks_path %>
				<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>
			</strong>
		<% end %>
	</p>
  <p id="notice"><%= notice %></p>
  <p id="alert"><%= alert %></p>

	<%= yield %>

</body>
</html>

app/views/projects/_form.html.haml
= form_for @project do |f|
	%p
		= f.error_messages

	%p
		= f.label :name
		= f.text_field :name

	.actions
		= f.submit 'Save'

app/views/projects/edit.html.haml
%h1 Edit!

= render 'form'

= link_to 'Nevermind', @project
|
= link_to 'View All', projects_path

app/views/projects/index.html.haml
%h1 Listing Projects

%p= link_to 'Make a New Project', new_project_path

%p= paginate @projects

%table
	%tr
		%th Name
		%th
		%th

	- @projects.each do |project|
		%tr
			%td= project.name
			%td= link_to 'Show', project
			%td= link_to 'Edit', edit_project_path(project)

%p= paginate @projects

%p= link_to 'Make a New Project', new_project_path

app/views/projects/new.html.haml
%h1 Create a New Project

= render 'form'

= link_to 'View All', projects_path

app/views/projects/show.html.haml
%h1= @project.name + ' Report'

- if current_user.admin?
	= form_tag(project_path(@project), :method => :get) do

		%p
			= label_tag :start_time
			= datetime_select :report, :start_time, :default => @start_time
	
		%p
			= label_tag :end_time
			= datetime_select :report, :end_time, :default => @end_time

		%p
			= submit_tag 'View'
	
	- unless @project_report.users.empty?
		%table
			%tr
				%th Email
				%th Hours Worked on this Project
			- @project_report.users.each do |user|
				%tr
					%td= link_to user.email, user_path(user)
					%td= rounded_hours_from_seconds @project_report.seconds_worked_for[user.id]

= link_to 'Edit', edit_project_path(@project)
|
= link_to 'View All', projects_path

app/views/time_blocks/_form.html.haml
= form_for @time_block do |f|
	%p
		= f.error_messages

	%p
		= f.label :project_id
		= f.select :project_id, @projects.collect{|p| [p.name, p.id] }, { :include_blank => true }
	
	%p 
		= f.label :start_time, 'Start Time'
		= f.datetime_select :start_time

	%p 
		= f.label :end_time, 'End Time'
		= f.datetime_select :end_time
		
	.actions
		= f.submit 'Save'

app/views/time_blocks/edit.html.haml
%h1 Edit!

= render 'form'

= link_to 'View All', time_blocks_path

app/views/time_blocks/index.html.haml
%h1 Listing Your Time Blocks

%p= paginate @time_blocks

%table
	%tr
		%th Project
		%th Start Time
		%th End Time
		%th 
		%th

	- @time_blocks.each do |time_block|
		%tr
			%td= link_to time_block.project.name, project_path(time_block.project)
			%td= display_time time_block.start_time
			%td= display_time time_block.end_time
			%td= link_to 'Edit', edit_time_block_path(time_block)
			%td= link_to 'Destroy', time_block, :method => :delete, :data => { :confirm => 'Are you sure?' }

%p= paginate @time_blocks

%p= link_to 'Record a New Time Block', new_time_block_path

app/views/time_blocks/new.html.haml
%h1 Make a New Time Block!

= render 'form'

= link_to 'Nevermind', time_blocks_path

app/views/users/_form.html.haml
= form_for @user do |f|
	%p
		= f.error_messages

	%p
		= f.label :email
		= f.text_field :email

	%p
		= f.label :admin
		= f.check_box :admin
	
	%p
		= f.submit

app/views/users/edit.html.haml
%h1 Edit!

= render 'form'

%p
	= link_to 'Nevermind', user_path(@user)
	|
	= link_to 'View All', users_path
	

app/views/users/index.html.haml
%h1 Users

%p= link_to 'Make a New User', new_user_path

%p= paginate @users 

%table
	%tr
		%th Email
		%th Admin?
		%th
		%th
	- @users.each do |user|
		%tr 
			%td= user.email
			%td= user.admin ? 'Aye!' : 'Nay!'
			%td= link_to 'View', user_path(user)
			- if current_user.admin?
				%td= link_to 'Edit', edit_user_path(user)
			
%p= paginate @users 

- if current_user.admin?
	%p= link_to 'Make a New User', new_user_path

app/views/users/new.html.haml
%h1 Create a New User

= render 'form'

%p
	= link_to 'View All', users_path
	

app/views/users/show.html.haml
%h1= @user.email + ' Report'

%i= @user.admin? ? 'Definitely Admin' : 'Not really admin'

- if current_user.admin?
	= form_tag(user_path(@user), :method => :get) do

		%p
			= label_tag :start_time
			= datetime_select :report, :start_time, :default => @start_time
	
		%p
			= label_tag :end_time
			= datetime_select :report, :end_time, :default => @end_time

		%p
			= submit_tag 'View'

	- unless @user_report.projects.empty?
		%table
			%tr
				%th Email
				%th Hours Worked on this Project
			- @user_report.projects.each do |project|
				%tr
					%td= link_to project.name, project_path(project)
					%td= rounded_hours_from_seconds @user_report.seconds_worked_for[project.id]

%p
	= link_to 'View All', users_path
	|
	= link_to 'Edit', edit_user_path(@user)